### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by arenas-guerrero-julian** [haydarai/tpcdi-kit#1]
Hi,

I execute the DIgen jar on Ubuntu:
```
java -jar DIGen.jar
```

But I get the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more
```

How could it be fixed?

Thanks

**Comment by stewartbryson** [comment]
@arenas-guerrero-julian Same issue here. Did you ever find a solution?

**Comment by arenas-guerrero-julian** [comment]
Unfortunately, I could not find a solution

**Comment by stewartbryson** [comment]
I just tested with a docker container running Java 8 and it works. Using any other version (including 11) on my Mac and it does not.

**Comment by arenas-guerrero-julian** [comment]
Hi @stewartbryson , thanks 

would it be possible to share the docker image?

**Comment by Jerry-liujie** [comment]
Java 8 also works for me. In my case, I also need to rename PDGF folder to pdgf (lowercase). Then you should be able to generate the data without problem.
